org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
kotlin.jvm.target.validation.mode=warning

# Desativa o observador contínuo de arquivos do Gradle (VFS watch) para evitar erros de 'Already watching path' em CI/CD
org.gradle.vfs.watch=false