# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: indice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'indice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cindice.proto\x12\x06\x61\x63\x65\x63mg\"A\n\x06Indice\x12\x10\n\x08url_base\x18\x01 \x01(\t\x12%\n\x07\x63roquis\x18\x02 \x03(\x0b\x32\x14.acecmg.ResumoCroqui\"\x8c\x01\n\x0cResumoCroqui\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x14\n\x0cnome_arquivo\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x17\n\x0f\x63hecksum_sha256\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61ta_update\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDICE']._serialized_start=24
  _globals['_INDICE']._serialized_end=89
  _globals['_RESUMOCROQUI']._serialized_start=92
  _globals['_RESUMOCROQUI']._serialized_end=232
# @@protoc_insertion_point(module_scope)
